use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMShowPageServices_Example' do
  pod 'AHFMShowPageServices', :path => '../'

  target 'AHFMShowPageServices_Tests' do
    inherit! :search_paths

    
  end
end
